version: '3.8'

services:
  backend:
    build: ./backend
    image: etty791/backend:latest
    ports:
      - "5001:5001"  # מיפוי פורט המחשב (ימין) לפורט הקונטיינר (שמאל)
    volumes:
      - db_data:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    image: etty791/frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # מונע דריסה של תיקיית המודולים שבתוך הקונטיינר
    stdin_open: true    # הכרחי כדי ש-React Scripts יעבוד בסביבת דוקר
    tty: true           # מאפשר הצגה תקינה של הלוגים של הפרונטנד
    depends_on:
      - backend         # מוודא שהבקאנד יעלה לפני הפרונטנד
volumes:
  db_data:
