version: '3.8'

services:
  backend:
    build: ./backend
    image: etty791/backend:latest
    ports:
      - "5001:5001"
    volumes:
      - db_data:/app/data  
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: sh -c "mkdir -p data && sed -i 's|sqlite:///todo.db|sqlite:///data/todo.db|g' app.py && flask run --host=0.0.0.0 --port=5001"

  frontend:
    build: ./frontend
    image: etty791/frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # מונע דריסה של תיקיית המודולים שבתוך הקונטיינר
    stdin_open: true    # הכרחי כדי ש-React Scripts יעבוד בסביבת דוקר
    tty: true           # מאפשר הצגה תקינה של הלוגים של הפרונטנד
    depends_on:
      - backend         # מוודא שהבקאנד יעלה לפני הפרונטנד
volumes:
  db_data:
